[alias]
bex = "build --release --example"
br = "build --release"
ef = "espflash --release --tool cargo --chip esp32"
em = "espmonitor --release --chip esp32 --no-reset"

[unstable]
build-std = ["core"]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "debuginfo=0",
  "-C", "link-arg=-Wl,-Tlink.x",
  "--emit", "llvm-bc,link",
]
target = "xtensa-esp32-none-elf"
# target = "xtensa-esp32s2-none-elf"
